version: '3'

networks:
  dockerapi-dev:
    driver: bridge

services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "userbook"
      POSTGRES_PASSWORD: "userbook"
      POSTGRES_DB: "userbook"
    networks:
      - dockerapi-dev  